// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppConfig = { id: string, name: string, launchers: Array<Launcher>, };

export type AppStateData = { data: Array<AppConfig>, };

export type ChromeLauncher = { action: string, profile: string | null, tab_group: TabGroup | null, links: Array<Link>, };

export type Launcher = { "appName": "chrome" } & ChromeLauncher | { "appName": "vs-code" } & VsCodeLauncher;

export type Link = { url: string, };

export type TabGroup = { name: string, color: string | null, };

export type VsCodeLauncher = { action: string, path: string | null, };
