// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppError = { "StartupError": { details: string, } } | { "RuntimeError": { details: string, } } | { "ResourceNotFound": { details: string, } } | { "InvalidInput": { details: string, } } | { "GenericError": { details: string, } } | { "InvalidConfiguration": { field: string, reason: string, field_label: string | null, } } | { "IoError": { path: string, details: string, } } | { "DeserializationError": { details: string, } };

export type AppStateData = { app_version: string, data: Array<WorkspaceConfig>, };

export type ChromeLauncher = { action: LauncherAction, profile: string | null, tab_group: TabGroup | null, links: Array<Link>, };

export type ChromeProfileDto = { profile_name: string, full_name: string, };

export type CreateWorkspacePayload = { name: string, launchers: Array<Launcher>, };

export type Launcher = { "appName": "chrome" } & ChromeLauncher | { "appName": "vs-code" } & VsCodeLauncher;

export type LauncherAction = "open";

export type Link = { url: string, };

export type TabGroup = { name: string, color: string | null, };

export type VsCodeLauncher = { action: LauncherAction, path: string | null, };

export type WorkspaceConfig = { id: string, name: string, launchers: Array<Launcher>, };
